version: '3'
services:
  db:
    image: postgres
    container_name: orders-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
